version: "2"

run:
  tests: false

linters:
  default: none
  enable:
    - errorlint
    - govet
    - ineffassign
    - misspell
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
