package analytics

var analyticsSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS analytics_runs (
	  run_id TEXT PRIMARY KEY,
	  started_at TEXT NOT NULL,
	  completed_at TEXT NOT NULL,
	  operation TEXT NOT NULL,
	  surface TEXT NOT NULL,
	  profile TEXT NOT NULL,
	  goal_hash TEXT NOT NULL,
	  goal_length_chars INTEGER NOT NULL,
	  discovery_mode TEXT NOT NULL,
	  seed_present INTEGER NOT NULL,
	  host TEXT NOT NULL DEFAULT '',
	  selected_url TEXT NOT NULL,
	  provider TEXT NOT NULL,
	  failure_class TEXT NOT NULL DEFAULT '',
	  success INTEGER NOT NULL,
	  trace_id TEXT NOT NULL,
	  latency_ms INTEGER NOT NULL,
	  packet_bytes INTEGER NOT NULL,
	  final_context_chars INTEGER NOT NULL,
	  chunk_count INTEGER NOT NULL,
	  source_count INTEGER NOT NULL,
	  link_count INTEGER NOT NULL,
	  proof_ref_count INTEGER NOT NULL,
	  proof_usable INTEGER NOT NULL,
	  public_bootstrap_used INTEGER NOT NULL,
	  local_memory_used INTEGER NOT NULL,
	  topic_node_used INTEGER NOT NULL,
	  same_site_recovery_used INTEGER NOT NULL,
	  candidate_count INTEGER NOT NULL,
	  raw_fetch_chars INTEGER NOT NULL,
	  raw_fetch_bytes INTEGER NOT NULL,
	  reduced_chars INTEGER NOT NULL,
	  reduced_node_count INTEGER NOT NULL,
	  memory_document_count INTEGER NOT NULL,
	  memory_embedding_count INTEGER NOT NULL,
	  memory_topic_node_count INTEGER NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_analytics_runs_completed_at ON analytics_runs(completed_at)`,
	`CREATE INDEX IF NOT EXISTS idx_analytics_runs_operation ON analytics_runs(operation)`,
	`CREATE INDEX IF NOT EXISTS idx_analytics_runs_host ON analytics_runs(host)`,
	`CREATE INDEX IF NOT EXISTS idx_analytics_runs_provider ON analytics_runs(provider)`,
	`CREATE TABLE IF NOT EXISTS analytics_stage_events (
	  id INTEGER PRIMARY KEY AUTOINCREMENT,
	  run_id TEXT NOT NULL,
	  stage TEXT NOT NULL,
	  started_at TEXT NOT NULL,
	  completed_at TEXT NOT NULL,
	  latency_ms INTEGER NOT NULL,
	  item_count INTEGER NOT NULL,
	  status TEXT NOT NULL,
	  metadata_json TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_analytics_stage_events_run_id ON analytics_stage_events(run_id)`,
}
